### PR TITLE
Updated docs and Python scripts

### PR DESCRIPTION
**Pull request by BitYog**

### CODE REVIEW

**Comment by ankitjain28may** [comment]
@BitYog Can you please resolve the conflicts, so i can merge the PR.

**Comment by ankitjain28may** [comment]
n please squash your commits

**Comment by BitYog** [comment]
I'll need to open a new Pull Request
Please merge that one

**Comment by BitYog** [comment]
Ignore the above comment. I've resolved the conflicts. You'll need to squash the commits.

**Comment by BitYog** [comment]
Thanks Ankit... This was my first Pull Request that got merged.

**Comment by ankitjain28may** [comment]
@BitYog Thanks for the fixes, Keep Coding and Keep Learning.

**Pull request merged**
