### PR TITLE
Youtube playlist

### PR DESCRIPTION
**Pull request by Pablololo12**
A simple Python Script to play music from youtube playlist.

### CODE REVIEW

**Comment by ankitjain28may** [comment]
@Pablololo12 Thanks for your contribution :)

**Comment by ankitjain28may** [comment]
Hey, can you pls fix this issue... I am getting this issue while trying to play a playlist.
image

**Comment by ankitjain28may** [comment]
Please add a README.md file

**Comment by Pablololo12** [comment]
Hi! I've been researching and I think it's a problem with mpv version. What
version are you running?

2017-10-01 10:48 GMT+02:00 Ankit Jain <notifications@github.com>:

**Comment by ankitjain28may** [comment]
Hi, Umm, I am not confirm about the version, It looks like this--
image
May be it requires some dependencies and all, can you pls add the README.md ?

**Comment by Pablololo12** [comment]
https://github.com/Pablololo12/pythonResources/tree/youtube-playlist/Play%20Youtube%20Playlist Try with MPV >= 0.25.0 and youtube-dl >= 2017.05.14
It works fine for me on Mac and Ubuntu

**Comment by ankitjain28may** [comment]
Ok

**Comment by ankitjain28may** [comment]
Ohh yes, It worked now, can you please make a PR with the added README.md.

**Pull request merged**
